"""Route-index v2 builder (Bx1a).

Compiles a machine-readable route-index.json from:
  - agent-docs/routing-map.md (YAML-in-markdown, generated by /analyze-synthesize)
  - agent-docs/.analysis-state.md (optional, for recursive subsystem metadata)

The route-index is consumed by the PreToolUse hook for path-aware
routing and by future Bx adaptive wiring.

Design:
  - Deterministic: same inputs → same output
  - Faithful: values derived directly from routing-map.md, no inference
  - Defensive: malformed input → clear error, not crash
  - Inspectable: JSON with readable field names
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


@dataclass
class SubsystemRoute:
    """One subsystem's routing entry."""
    subsystem: str
    doc_path: str
    role: str = ""
    owns_paths: list[str] = field(default_factory=list)
    key_files: list[str] = field(default_factory=list)
    key_tests: list[str] = field(default_factory=list)
    common_tasks: list[str] = field(default_factory=list)
    brief_paths: list[str] = field(default_factory=list)
    recursive_children: list[str] = field(default_factory=list)


@dataclass
class PatternRoute:
    """One pattern's routing entry."""
    pattern_name: str
    doc_anchor: str = ""
    subsystem: str = ""
    template_file: str = ""
    registration: str = ""
    test_template: str = ""
    file_count: str = ""


@dataclass
class RouteIndex:
    """Complete route-index v2."""
    version: int = 2
    generated_from: dict = field(default_factory=dict)
    subsystem_routes: list[SubsystemRoute] = field(default_factory=list)
    pattern_routes: list[PatternRoute] = field(default_factory=list)
    fallbacks: dict = field(default_factory=dict)
    fallback_hint: str = ""
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "version": self.version,
            "generated_from": self.generated_from,
            "subsystem_routes": [asdict(r) for r in self.subsystem_routes],
            "pattern_routes": [asdict(r) for r in self.pattern_routes],
            "fallbacks": self.fallbacks,
            "fallback_hint": self.fallback_hint,
            "errors": self.errors,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _extract_yaml_block(content: str) -> str | None:
    """Extract the first YAML code block from markdown content.

    Looks for ```yaml ... ``` fences. Returns the YAML text or None.
    """
    match = re.search(r"```yaml\s*\n(.*?)```", content, re.DOTALL)
    if match:
        return match.group(1)
    return None


def _parse_routing_map(routing_map_path: Path) -> tuple[list[dict], list[dict], list[str]]:
    """Parse routing-map.md and extract subsystem + pattern routing entries.

    Returns (subsystem_entries, pattern_entries, errors).
    """
    errors: list[str] = []

    if not routing_map_path.exists():
        return [], [], [f"routing-map.md not found at {routing_map_path}"]

    try:
        content = routing_map_path.read_text(encoding="utf-8")
    except OSError as e:
        return [], [], [f"Failed to read routing-map.md: {e}"]

    yaml_text = _extract_yaml_block(content)
    if yaml_text is None:
        return [], [], ["No ```yaml``` block found in routing-map.md"]

    try:
        data = yaml.safe_load(yaml_text)
    except yaml.YAMLError as e:
        return [], [], [f"YAML parse error in routing-map.md: {e}"]

    if not isinstance(data, dict):
        return [], [], [f"routing-map.md YAML root is not a dict: {type(data).__name__}"]

    subsystems = data.get("subsystem_routing", [])
    patterns = data.get("pattern_routing", [])

    if not isinstance(subsystems, list):
        errors.append(f"subsystem_routing is not a list: {type(subsystems).__name__}")
        subsystems = []

    if not isinstance(patterns, list):
        errors.append(f"pattern_routing is not a list: {type(patterns).__name__}")
        patterns = []

    return subsystems, patterns, errors


def _parse_recursion_from_analysis_state(state_path: Path) -> dict[str, list[str]]:
    """Extract recursive subsystem children from .analysis-state.md.

    Handles two formats:
    1. Inline in subsystems_completed:
       "retrieval-rag (recursive: vector, web-search, loaders)"
    2. Structured recursion_applied block (from deep-dive prompt):
       recursion_applied:
         - parent: retrieval-rag
           children:
             - name: vector

    Returns {parent_name: [child_name, ...]}. Empty dict if no recursion
    or file not found.
    """
    if not state_path.exists():
        return {}

    try:
        content = state_path.read_text(encoding="utf-8")
    except OSError:
        return {}

    # Extract YAML frontmatter between --- fences
    match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not match:
        yaml_text = _extract_yaml_block(content)
        if not yaml_text:
            return {}
    else:
        yaml_text = match.group(1)

    try:
        data = yaml.safe_load(yaml_text)
    except yaml.YAMLError:
        return {}

    if not isinstance(data, dict):
        return {}

    result: dict[str, list[str]] = {}

    # Format 1: inline in subsystems_completed
    # The YAML parser may interpret "name (recursive: a, b)" as either:
    #   - a string (if quoted): "name (recursive: a, b)"
    #   - a dict (unquoted): {"name (recursive": "a, b)"}
    for entry in data.get("subsystems_completed", []):
        if isinstance(entry, str) and "(recursive:" in entry:
            # Properly quoted string case
            match_rec = re.match(r"^(.+?)\s*\(recursive:\s*(.+?)\)\s*$", entry)
            if match_rec:
                parent = match_rec.group(1).strip()
                children = [c.strip() for c in match_rec.group(2).split(",") if c.strip()]
                if parent and children:
                    result[parent] = children
        elif isinstance(entry, dict):
            # YAML misparse case: {"name (recursive": "child1, child2)"}
            for key, value in entry.items():
                if "(recursive" in key and isinstance(value, str):
                    parent = key.split("(recursive")[0].strip()
                    # Value has trailing ")" from the YAML misparse
                    children_str = value.rstrip(")").strip()
                    children = [c.strip() for c in children_str.split(",") if c.strip()]
                    if parent and children:
                        result[parent] = children

    # Format 2: structured recursion_applied block
    for entry in data.get("recursion_applied", []):
        if isinstance(entry, dict):
            parent = entry.get("parent", "")
            children = []
            for child in entry.get("children", []):
                if isinstance(child, dict):
                    children.append(child.get("name", ""))
                elif isinstance(child, str):
                    children.append(child)
            if parent and children:
                result[parent] = children

    return result


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """Convert a name to a URL-friendly slug for doc anchors."""
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug


def build_route_index(
    routing_map_path: Path,
    analysis_state_path: Path | None = None,
) -> RouteIndex:
    """Build a route-index v2 from routing-map.md and optionally .analysis-state.md.

    Args:
        routing_map_path: Path to agent-docs/routing-map.md.
        analysis_state_path: Path to agent-docs/.analysis-state.md (optional).

    Returns:
        RouteIndex with all routing entries, or errors if parsing failed.
    """
    subsystem_entries, pattern_entries, errors = _parse_routing_map(routing_map_path)

    # Parse recursion metadata if available
    recursion: dict[str, list[str]] = {}
    if analysis_state_path:
        recursion = _parse_recursion_from_analysis_state(analysis_state_path)

    # Build subsystem routes
    subsystem_routes: list[SubsystemRoute] = []
    for entry in subsystem_entries:
        if not isinstance(entry, dict):
            errors.append(f"Skipping non-dict subsystem entry: {entry}")
            continue

        name = str(entry.get("name", ""))
        if not name:
            errors.append(f"Skipping subsystem entry with no name: {entry}")
            continue

        # Derive doc path from name
        safe_name = _slugify(name)
        doc_path = entry.get("doc", f"agent-docs/subsystems/{safe_name}.md")

        owns = [str(p) for p in entry.get("owns_paths", [])]
        # brief_paths: use explicit value from routing-map if provided,
        # otherwise fall back to owns_paths for backward compatibility.
        explicit_brief = entry.get("brief_paths")
        if isinstance(explicit_brief, list) and explicit_brief:
            brief = [str(p) for p in explicit_brief]
        else:
            brief = list(owns)

        subsystem_routes.append(SubsystemRoute(
            subsystem=name,
            doc_path=doc_path,
            role=str(entry.get("role", "")),
            owns_paths=owns,
            key_files=[str(f) for f in entry.get("key_files", [])],
            key_tests=[str(t) for t in entry.get("key_tests", [])],
            common_tasks=[str(t) for t in entry.get("common_tasks", [])],
            brief_paths=brief,
            recursive_children=recursion.get(name, []),
        ))

    # Sort subsystem routes by name for deterministic output
    subsystem_routes.sort(key=lambda r: r.subsystem)

    # Build pattern routes
    pattern_routes: list[PatternRoute] = []
    for entry in pattern_entries:
        if not isinstance(entry, dict):
            errors.append(f"Skipping non-dict pattern entry: {entry}")
            continue

        pattern_name = str(entry.get("pattern", ""))
        if not pattern_name:
            errors.append(f"Skipping pattern entry with no name: {entry}")
            continue

        slug = _slugify(pattern_name)
        doc_anchor = f"patterns.md#{slug}"

        pattern_routes.append(PatternRoute(
            pattern_name=pattern_name,
            doc_anchor=doc_anchor,
            subsystem=str(entry.get("subsystem", "")),
            template_file=str(entry.get("template_file", "")),
            registration=str(entry.get("registration", "")),
            test_template=str(entry.get("test_template", "")),
            file_count=str(entry.get("file_count", "")),
        ))

    # Sort pattern routes by name for deterministic output
    pattern_routes.sort(key=lambda r: r.pattern_name)

    # Build sources list
    generated_from: dict = {
        "routing_map": str(routing_map_path),
    }
    if analysis_state_path and analysis_state_path.exists():
        generated_from["analysis_state"] = str(analysis_state_path)

    return RouteIndex(
        version=2,
        generated_from=generated_from,
        subsystem_routes=subsystem_routes,
        pattern_routes=pattern_routes,
        fallbacks={
            "nano": "agent-docs/agent-context-nano.md",
            "agent_context": "agent-docs/agent-context.md",
            "structural_profiles": "agent-docs/structural-profiles.md",
        },
        fallback_hint=(
            "Codebase context in CLAUDE.md (nano-digest). "
            "For deeper context: agent-docs/agent-context.md"
        ),
        errors=errors,
    )


def save_route_index(index: RouteIndex, output_path: Path) -> Path:
    """Write route-index.json."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(index.to_json() + "\n", encoding="utf-8")
    return output_path
