"""Route-index v2 builder with routing lock support.

Compiles a machine-readable route-index.json from:
  - agent-docs/routing-map.md (YAML-in-markdown, generated by /analyze-synthesize)
  - agent-docs/routing-lock.yaml (stable routing semantics, auto-generated on first run)
  - agent-docs/.analysis-state.md (optional, for recursive subsystem metadata)

Three-layer model:
  - routing-map.md = latest synthesized candidate (may drift across re-runs)
  - routing-lock.yaml = stable reviewed routing semantics (locked fields)
  - route-index.json = compiled runtime artifact from both

Locked fields (from routing-lock.yaml when present):
  - subsystem: role, common_tasks, brief_paths

Fresh fields (always from routing-map.md):
  - subsystem: doc_path, owns_paths, key_files, key_tests, recursive_children
  - pattern: all fields (matched by exact pattern_name)

Pattern locking limitation:
  Patterns are matched by exact name. If synthesis renames or drops a
  pattern, it becomes stale + new — not a preserved rename. The lock
  stabilizes subsystem semantics reliably but only tracks pattern
  existence, not identity across renames.

Design:
  - Deterministic: same inputs → same output
  - Defensive: malformed lock → warn and skip, not silently overwrite
  - Inspectable: JSON/YAML with readable field names
  - Stable: locked subsystem semantics survive re-synthesis drift
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


@dataclass
class SubsystemRoute:
    """One subsystem's routing entry."""
    subsystem: str
    doc_path: str
    role: str = ""
    owns_paths: list[str] = field(default_factory=list)
    key_files: list[str] = field(default_factory=list)
    key_tests: list[str] = field(default_factory=list)
    common_tasks: list[str] = field(default_factory=list)
    brief_paths: list[str] = field(default_factory=list)
    recursive_children: list[str] = field(default_factory=list)


@dataclass
class PatternRoute:
    """One pattern's routing entry."""
    pattern_name: str
    doc_anchor: str = ""
    subsystem: str = ""
    template_file: str = ""
    registration: str = ""
    test_template: str = ""
    file_count: str = ""


@dataclass
class RouteIndex:
    """Complete route-index v2."""
    version: int = 2
    generated_from: dict = field(default_factory=dict)
    subsystem_routes: list[SubsystemRoute] = field(default_factory=list)
    pattern_routes: list[PatternRoute] = field(default_factory=list)
    fallbacks: dict = field(default_factory=dict)
    fallback_hint: str = ""
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "version": self.version,
            "generated_from": self.generated_from,
            "subsystem_routes": [asdict(r) for r in self.subsystem_routes],
            "pattern_routes": [asdict(r) for r in self.pattern_routes],
            "fallbacks": self.fallbacks,
            "fallback_hint": self.fallback_hint,
            "errors": self.errors,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _extract_yaml_block(content: str) -> str | None:
    """Extract the first YAML code block from markdown content.

    Looks for ```yaml ... ``` fences. Returns the YAML text or None.
    """
    match = re.search(r"```yaml\s*\n(.*?)```", content, re.DOTALL)
    if match:
        return match.group(1)
    return None


def _parse_routing_map(routing_map_path: Path) -> tuple[list[dict], list[dict], list[str]]:
    """Parse routing-map.md and extract subsystem + pattern routing entries.

    Returns (subsystem_entries, pattern_entries, errors).
    """
    errors: list[str] = []

    if not routing_map_path.exists():
        return [], [], [f"routing-map.md not found at {routing_map_path}"]

    try:
        content = routing_map_path.read_text(encoding="utf-8")
    except OSError as e:
        return [], [], [f"Failed to read routing-map.md: {e}"]

    yaml_text = _extract_yaml_block(content)
    if yaml_text is None:
        return [], [], ["No ```yaml``` block found in routing-map.md"]

    try:
        data = yaml.safe_load(yaml_text)
    except yaml.YAMLError as e:
        return [], [], [f"YAML parse error in routing-map.md: {e}"]

    if not isinstance(data, dict):
        return [], [], [f"routing-map.md YAML root is not a dict: {type(data).__name__}"]

    subsystems = data.get("subsystem_routing", [])
    patterns = data.get("pattern_routing", [])

    if not isinstance(subsystems, list):
        errors.append(f"subsystem_routing is not a list: {type(subsystems).__name__}")
        subsystems = []

    if not isinstance(patterns, list):
        errors.append(f"pattern_routing is not a list: {type(patterns).__name__}")
        patterns = []

    return subsystems, patterns, errors


def _parse_recursion_from_analysis_state(state_path: Path) -> dict[str, list[str]]:
    """Extract recursive subsystem children from .analysis-state.md.

    Handles two formats:
    1. Inline in subsystems_completed:
       "retrieval-rag (recursive: vector, web-search, loaders)"
    2. Structured recursion_applied block (from deep-dive prompt):
       recursion_applied:
         - parent: retrieval-rag
           children:
             - name: vector

    Returns {parent_name: [child_name, ...]}. Empty dict if no recursion
    or file not found.
    """
    if not state_path.exists():
        return {}

    try:
        content = state_path.read_text(encoding="utf-8")
    except OSError:
        return {}

    # Extract YAML frontmatter between --- fences
    match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not match:
        yaml_text = _extract_yaml_block(content)
        if not yaml_text:
            return {}
    else:
        yaml_text = match.group(1)

    try:
        data = yaml.safe_load(yaml_text)
    except yaml.YAMLError:
        return {}

    if not isinstance(data, dict):
        return {}

    result: dict[str, list[str]] = {}

    # Format 1: inline in subsystems_completed
    # The YAML parser may interpret "name (recursive: a, b)" as either:
    #   - a string (if quoted): "name (recursive: a, b)"
    #   - a dict (unquoted): {"name (recursive": "a, b)"}
    for entry in data.get("subsystems_completed", []):
        if isinstance(entry, str) and "(recursive:" in entry:
            # Properly quoted string case
            match_rec = re.match(r"^(.+?)\s*\(recursive:\s*(.+?)\)\s*$", entry)
            if match_rec:
                parent = match_rec.group(1).strip()
                children = [c.strip() for c in match_rec.group(2).split(",") if c.strip()]
                if parent and children:
                    result[parent] = children
        elif isinstance(entry, dict):
            # YAML misparse case: {"name (recursive": "child1, child2)"}
            for key, value in entry.items():
                if "(recursive" in key and isinstance(value, str):
                    parent = key.split("(recursive")[0].strip()
                    # Value has trailing ")" from the YAML misparse
                    children_str = value.rstrip(")").strip()
                    children = [c.strip() for c in children_str.split(",") if c.strip()]
                    if parent and children:
                        result[parent] = children

    # Format 2: structured recursion_applied block
    for entry in data.get("recursion_applied", []):
        if isinstance(entry, dict):
            parent = entry.get("parent", "")
            children = []
            for child in entry.get("children", []):
                if isinstance(child, dict):
                    children.append(child.get("name", ""))
                elif isinstance(child, str):
                    children.append(child)
            if parent and children:
                result[parent] = children

    return result


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """Convert a name to a URL-friendly slug for doc anchors."""
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug


def build_route_index(
    routing_map_path: Path,
    analysis_state_path: Path | None = None,
) -> RouteIndex:
    """Build a route-index v2 from routing-map.md and optionally .analysis-state.md.

    Args:
        routing_map_path: Path to agent-docs/routing-map.md.
        analysis_state_path: Path to agent-docs/.analysis-state.md (optional).

    Returns:
        RouteIndex with all routing entries, or errors if parsing failed.
    """
    subsystem_entries, pattern_entries, errors = _parse_routing_map(routing_map_path)

    # Parse recursion metadata if available
    recursion: dict[str, list[str]] = {}
    if analysis_state_path:
        recursion = _parse_recursion_from_analysis_state(analysis_state_path)

    # Build subsystem routes
    subsystem_routes: list[SubsystemRoute] = []
    for entry in subsystem_entries:
        if not isinstance(entry, dict):
            errors.append(f"Skipping non-dict subsystem entry: {entry}")
            continue

        name = str(entry.get("name", ""))
        if not name:
            errors.append(f"Skipping subsystem entry with no name: {entry}")
            continue

        # Derive doc path from name
        safe_name = _slugify(name)
        doc_path = entry.get("doc", f"agent-docs/subsystems/{safe_name}.md")

        owns = [str(p) for p in entry.get("owns_paths", [])]
        # brief_paths: use explicit value from routing-map if provided,
        # otherwise fall back to owns_paths for backward compatibility.
        explicit_brief = entry.get("brief_paths")
        if isinstance(explicit_brief, list) and explicit_brief:
            brief = [str(p) for p in explicit_brief]
        else:
            brief = list(owns)

        subsystem_routes.append(SubsystemRoute(
            subsystem=name,
            doc_path=doc_path,
            role=str(entry.get("role", "")),
            owns_paths=owns,
            key_files=[str(f) for f in entry.get("key_files", [])],
            key_tests=[str(t) for t in entry.get("key_tests", [])],
            common_tasks=[str(t) for t in entry.get("common_tasks", [])],
            brief_paths=brief,
            recursive_children=recursion.get(name, []),
        ))

    # Sort subsystem routes by name for deterministic output
    subsystem_routes.sort(key=lambda r: r.subsystem)

    # Build pattern routes
    pattern_routes: list[PatternRoute] = []
    for entry in pattern_entries:
        if not isinstance(entry, dict):
            errors.append(f"Skipping non-dict pattern entry: {entry}")
            continue

        pattern_name = str(entry.get("pattern", ""))
        if not pattern_name:
            errors.append(f"Skipping pattern entry with no name: {entry}")
            continue

        slug = _slugify(pattern_name)
        doc_anchor = f"patterns.md#{slug}"

        pattern_routes.append(PatternRoute(
            pattern_name=pattern_name,
            doc_anchor=doc_anchor,
            subsystem=str(entry.get("subsystem", "")),
            template_file=str(entry.get("template_file", "")),
            registration=str(entry.get("registration", "")),
            test_template=str(entry.get("test_template", "")),
            file_count=str(entry.get("file_count", "")),
        ))

    # Sort pattern routes by name for deterministic output
    pattern_routes.sort(key=lambda r: r.pattern_name)

    # Build sources list
    generated_from: dict = {
        "routing_map": str(routing_map_path),
    }
    if analysis_state_path and analysis_state_path.exists():
        generated_from["analysis_state"] = str(analysis_state_path)

    return RouteIndex(
        version=2,
        generated_from=generated_from,
        subsystem_routes=subsystem_routes,
        pattern_routes=pattern_routes,
        fallbacks={
            "nano": "agent-docs/agent-context-nano.md",
            "agent_context": "agent-docs/agent-context.md",
            "structural_profiles": "agent-docs/structural-profiles.md",
        },
        fallback_hint=(
            "Codebase context in CLAUDE.md (nano-digest). "
            "For deeper context: agent-docs/agent-context.md"
        ),
        errors=errors,
    )


def save_route_index(index: RouteIndex, output_path: Path) -> Path:
    """Write route-index.json."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(index.to_json() + "\n", encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# Routing Lock
# ---------------------------------------------------------------------------


@dataclass
class ReconciliationReport:
    """Summary of lock vs candidate reconciliation."""
    lock_created: bool = False
    subsystems_matched: int = 0
    subsystems_new: int = 0
    subsystems_stale: int = 0
    patterns_matched: int = 0
    patterns_new: int = 0
    patterns_stale: int = 0
    locked_role_overrides: int = 0
    locked_common_tasks_overrides: int = 0
    locked_brief_paths_overrides: int = 0
    locked_pattern_name_overrides: int = 0
    stale_subsystems: list[str] = field(default_factory=list)
    stale_patterns: list[str] = field(default_factory=list)
    new_subsystems: list[str] = field(default_factory=list)
    new_patterns: list[str] = field(default_factory=list)


def load_routing_lock(lock_path: Path) -> tuple[str, dict | None]:
    """Load routing-lock.yaml.

    Returns (status, data) where status is one of:
      - "missing" — file does not exist (first run)
      - "malformed" — file exists but is not valid YAML or not a dict
      - "ok" — file loaded successfully

    Callers must distinguish missing (safe to create) from malformed
    (should warn, not silently overwrite).
    """
    if not lock_path.exists():
        return ("missing", None)
    try:
        content = lock_path.read_text(encoding="utf-8")
        data = yaml.safe_load(content)
        if not isinstance(data, dict):
            return ("malformed", None)
        return ("ok", data)
    except (OSError, yaml.YAMLError):
        return ("malformed", None)


def derive_lock_from_index(index: RouteIndex) -> dict:
    """Derive a routing-lock.yaml structure from a built RouteIndex.

    Extracts only the locked semantic fields:
      - subsystems: role, common_tasks, brief_paths
      - patterns: pattern_name
    """
    lock: dict = {"version": 1, "subsystems": {}, "patterns": {}}

    for route in index.subsystem_routes:
        lock["subsystems"][route.subsystem] = {
            "role": route.role,
            "common_tasks": list(route.common_tasks),
            "brief_paths": list(route.brief_paths),
        }

    for pattern in index.pattern_routes:
        lock["patterns"][pattern.pattern_name] = {
            "pattern_name": pattern.pattern_name,
        }

    return lock


def save_routing_lock(lock: dict, lock_path: Path) -> Path:
    """Write routing-lock.yaml with deterministic key ordering."""
    lock_path.parent.mkdir(parents=True, exist_ok=True)

    # Sort subsystems and patterns for deterministic output
    ordered: dict = {"version": lock.get("version", 1)}

    subsystems = lock.get("subsystems", {})
    ordered["subsystems"] = {k: subsystems[k] for k in sorted(subsystems)}

    patterns = lock.get("patterns", {})
    ordered["patterns"] = {k: patterns[k] for k in sorted(patterns)}

    lock_path.write_text(
        yaml.dump(ordered, default_flow_style=False, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return lock_path


def merge_candidate_with_lock(
    candidate: RouteIndex,
    lock: dict,
) -> tuple[RouteIndex, ReconciliationReport]:
    """Merge a candidate RouteIndex with a routing lock.

    Lock wins for semantic fields (role, common_tasks, brief_paths, pattern_name).
    Candidate wins for structural fields (owns_paths, key_files, doc_path, etc.).

    New entries (in candidate but not lock) are included in the result.
    Stale entries (in lock but not candidate) are excluded from the result.

    Returns (merged_index, reconciliation_report).
    """
    report = ReconciliationReport()
    locked_subs = lock.get("subsystems", {})
    locked_pats = lock.get("patterns", {})

    # --- Merge subsystems ---
    candidate_sub_names = {r.subsystem for r in candidate.subsystem_routes}
    locked_sub_names = set(locked_subs.keys())

    matched_subs = candidate_sub_names & locked_sub_names
    new_subs = candidate_sub_names - locked_sub_names
    stale_subs = locked_sub_names - candidate_sub_names

    report.subsystems_matched = len(matched_subs)
    report.subsystems_new = len(new_subs)
    report.subsystems_stale = len(stale_subs)
    report.stale_subsystems = sorted(stale_subs)
    report.new_subsystems = sorted(new_subs)

    merged_subsystems: list[SubsystemRoute] = []
    for route in candidate.subsystem_routes:
        if route.subsystem in locked_subs:
            locked = locked_subs[route.subsystem]
            # Lock wins for semantic fields
            locked_role = locked.get("role")
            if locked_role is not None and locked_role != route.role:
                report.locked_role_overrides += 1
            locked_tasks = locked.get("common_tasks")
            if locked_tasks is not None and locked_tasks != route.common_tasks:
                report.locked_common_tasks_overrides += 1
            locked_brief = locked.get("brief_paths")
            if locked_brief is not None and locked_brief != route.brief_paths:
                report.locked_brief_paths_overrides += 1

            merged_subsystems.append(SubsystemRoute(
                subsystem=route.subsystem,
                # Structural fields: always from candidate
                doc_path=route.doc_path,
                owns_paths=route.owns_paths,
                key_files=route.key_files,
                key_tests=route.key_tests,
                recursive_children=route.recursive_children,
                # Semantic fields: lock if present, else candidate
                role=locked.get("role", route.role) if locked.get("role") is not None else route.role,
                common_tasks=locked.get("common_tasks", route.common_tasks) if locked.get("common_tasks") is not None else route.common_tasks,
                brief_paths=locked.get("brief_paths", route.brief_paths) if locked.get("brief_paths") is not None else route.brief_paths,
            ))
        else:
            # New subsystem — use candidate as-is
            merged_subsystems.append(route)

    merged_subsystems.sort(key=lambda r: r.subsystem)

    # --- Merge patterns ---
    candidate_pat_names = {p.pattern_name for p in candidate.pattern_routes}
    locked_pat_names = set(locked_pats.keys())

    matched_pats = candidate_pat_names & locked_pat_names
    new_pats = candidate_pat_names - locked_pat_names
    stale_pats = locked_pat_names - candidate_pat_names

    report.patterns_matched = len(matched_pats)
    report.patterns_new = len(new_pats)
    report.patterns_stale = len(stale_pats)
    report.stale_patterns = sorted(stale_pats)
    report.new_patterns = sorted(new_pats)

    merged_patterns: list[PatternRoute] = []
    for pattern in candidate.pattern_routes:
        if pattern.pattern_name in locked_pats:
            locked = locked_pats[pattern.pattern_name]
            locked_name = locked.get("pattern_name")
            if locked_name and locked_name != pattern.pattern_name:
                report.locked_pattern_name_overrides += 1
            # Pattern name from lock; structural fields from candidate
            merged_patterns.append(PatternRoute(
                pattern_name=locked_name if locked_name else pattern.pattern_name,
                doc_anchor=pattern.doc_anchor,
                subsystem=pattern.subsystem,
                template_file=pattern.template_file,
                registration=pattern.registration,
                test_template=pattern.test_template,
                file_count=pattern.file_count,
            ))
        else:
            # New pattern — use candidate as-is
            merged_patterns.append(pattern)

    merged_patterns.sort(key=lambda r: r.pattern_name)

    merged_index = RouteIndex(
        version=candidate.version,
        generated_from=candidate.generated_from,
        subsystem_routes=merged_subsystems,
        pattern_routes=merged_patterns,
        fallbacks=candidate.fallbacks,
        fallback_hint=candidate.fallback_hint,
        errors=candidate.errors,
    )

    return merged_index, report


def update_lock_with_new_entries(
    lock: dict,
    index: RouteIndex,
    report: ReconciliationReport,
) -> dict:
    """Auto-append new entries from the merged index into the lock.

    New subsystems and patterns are added. Stale entries are retained
    in the lock but excluded from route-index (handled by merge).
    """
    updated = {
        "version": lock.get("version", 1),
        "subsystems": dict(lock.get("subsystems", {})),
        "patterns": dict(lock.get("patterns", {})),
    }

    # Add new subsystems
    for name in report.new_subsystems:
        route = next((r for r in index.subsystem_routes if r.subsystem == name), None)
        if route:
            updated["subsystems"][name] = {
                "role": route.role,
                "common_tasks": list(route.common_tasks),
                "brief_paths": list(route.brief_paths),
            }

    # Add new patterns
    for name in report.new_patterns:
        pattern = next((p for p in index.pattern_routes if p.pattern_name == name), None)
        if pattern:
            updated["patterns"][name] = {
                "pattern_name": pattern.pattern_name,
            }

    return updated
